[package]
name = "yew-mermaid-preview"
publish = false
version = "0.1.0"
readme = "../../Readme.md"
edition = "2018"

[dependencies]
yew = { workspace = true }
yew-mermaid = { version = "0.2", path = "../yew-mermaid" }
web-sys = { version = "0.3.66", features = ["Window", "Document"] }
